---
- hosts: localhost
  vars_prompt:

          - name: username
            prompt: Username
            private: no

          - name: appname
            prompt: APP name
            private: no

          - name: url
            prompt: URL
            private: no
      
  tasks:

  - name: Create user
    ansible.builtin.user:
        name: '{{username}}'
        group: sudo
        
  - name: Download and unzip
    ansible.builtin.unarchive:
        src: '{{url}}'
        dest: /home/{{username}}
        remote_src: yes
        list_files: yes
    register: dest

  - name: Execute the script
    script: '{{dest.dest}}/{{dest.files[0]}}{{appname}}'

    